channels:
  - conda-forge
dependencies:
  - r-base=4.0.2
  - r-tidyverse
  - r-tidymodels
  - r-skimr
  - r-vip
  - r-lubridate
  - r-nycflights13
  - r-klaR
  - r-kknn
  - r-rpart
  - r-rpart.plot
  - r-ranger
  
